spring:
  main:
    banner-mode: "off"
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://database:5432/keyvalue?autoreconnect=true
    username: postgres
    password: testivilinsalasana
    driver-class-name: org.postgresql.Driver
  data:
    jpa:
      repositories:
        enabled: true
  flyway:
    url: jdbc:postgresql://database:5432/keyvalue
    user: postgres
    password: testivilinsalasana
keyvaluestore:
  restricted-key-values:
    - _version
    - _id